### ISSUE TITLE
Add references to dbuezas?

### ISSUE THREAD

**Issue by dwillmore** [watterott/LGT8F328P-Testing#1]
[This](url https://github.com/dbuezas/lgt8fx) is an attempt to cleanup and enhance the board support package for this family of processors--and the boards based on it.

It might be useful to reference it from the readme.md file.

Is Watterott considering making a board for this chip?  If so, please feel free to open an issue in the above repo and we'll try to add support for your board.

**Comment by awatterott** [comment]
Thank you for the info. I will add a link to the readme.
Yes, we have started to make a board, but currently it is not ready. 
We have done a translation of the latest datasheet: [pdf](https://github.com/watterott/LGT8F328P-Testing/raw/master/LGT8FX8P_databook_v1.0.5-English.pdf)

**Comment by dwillmore** [comment]
Wonderful, thank you.  

Once the board is further along and you know your pin to board layout, we can add support for it.  We'd be glad to help.

There are a few people working on datasheet translation over at [Issue #8](url https://github.com/dbuezas/lgt8fx/issues/8) if you are interested in working with others doing similar work.

**Comment by dbuezas** [comment]
We'll gladly add pictures and links to your board in the readme of the repo and, as dwillmore said, new board definitions if required.
Looking forward to see your new board!

**Comment by dwillmore** [comment]
Aren't both of you in DE?

**Comment by dbuezas** [comment]
True
